### ISSUE TITLE
SerialReader Class

### ISSUE THREAD

**Issue by wagnerdylan** [RIT-Space-Exploration/SPEXTRO_Ground_Station#1]
Add the code for this task in the serial_reader.py file.
Create a class named SerialReader that will handle data streaming in over a serial connection using PySerial. This class should take in the necessary information to initialize a Serial connection and a variable which will be used as a callback. Store the Serial connection object, the callback and a boolean which will be used as a condition (set to True) as instance variables (IE: self.xxxx). This class should include the following method:

read_data(self): This method should, in a while loop using the condition variable as the condition (1) Call .read(size=2) on the serial connection to grab the size of the incoming message. (2) Convert this raw bytes string to an int. (3) Use this size as the size parameter for the next .read(size=message_size) call. (4) pass the bytes string returned from the read call into the callback variable. 

Note: This read_data method will be running in a separate thread.

**Comment by ColtonGlasgow13** [comment]
I can give this a try, I don't have a lot of experience with things like it but I think I can figure things out.

**Comment by wagnerdylan** [comment]
Okay sounds good, feel free to ask about anything.

**Comment by ColtonGlasgow13** [comment]
Ok, sorry its been a while, I got sick over the last week, but I uploaded a very rough draft to the file, even though it seems suspiciously short. I also didn't know what you meant by using the condition variable as the condition, so I just made it a While True loop. Might have been a bad idea, so maybe don't run it.

**Comment by wagnerdylan** [comment]
I pushed some changes to the SerialReader class. Some syntax corrections and added a python decorator which wraps the read_data function to it gets launched in a thread. Let me know if you have any questions about it.

**Comment by ColtonGlasgow13** [comment]
I do have some questions about it, but I can probably just save it for our next meeting.
